version: '3'
services:

  repo:
    image: nginx:1.17
    ports:
    - "8081:80"
    restart: always
    volumes:
    - '/mnt/volume_pionux_repo/pionux-repo/repo:/home/repo'
    - '/mnt/volume_pionux_repo/pionux-repo/pionux-repo-docker/nginx/nginx.conf:/etc/nginx/nginx.conf'

  # fdroid-repo:
  #   image: hongsea/pionux-repo-docker:latest
  #   restart: always
  #   ports:
  #   - '873:8873'
  #   volumes:
  #   - './repo/:/pionux-mirror/repo/'